import admm
import numpy as np


class ItakuraSaitoDivergence(admm.UDFBase):
    r"""Itakura-Saito divergence: a Bregman divergence for spectral analysis.

    Mathematical definition:

        f(x) = Σᵢ [yᵢ/xᵢ − log(yᵢ/xᵢ) − 1]

    where y > 0 is the fixed reference (e.g., observed power spectrum)
    and x > 0 is the variable (e.g., model power spectrum).

    Behavior:
        x = y:         f(x) = 0           (minimum, perfect fit)
        xᵢ → 0⁺:      f → +∞             (penalizes underestimation)
        xᵢ → +∞:      f → +∞ (slowly)    (penalizes overestimation)
        xᵢ < yᵢ:      penalized more heavily than xᵢ > yᵢ

    This asymmetric behavior makes the Itakura-Saito divergence
    particularly suited for audio and spectral estimation, where
    underestimating energy is perceptually worse than overestimating.

    Gradient:

        ∇f(x)ᵢ = −yᵢ/xᵢ² + 1/xᵢ = (xᵢ − yᵢ) / xᵢ²

    Properties:
    - Scale-invariant: f(αx; αy) = f(x; y) for any α > 0
    - Not symmetric: f(x; y) ≠ f(y; x)
    - A Bregman divergence generated by −Σ log(xᵢ)
    - Corresponds to ML estimation under multiplicative Gamma noise

    Parameters
    ----------
    arg : admm.Var or expression
        The variable x (must be positive).
    y : array_like
        The fixed reference values (must be positive).
    """

    def __init__(self, arg, y):
        self.arg = arg
        self.y = np.asarray(y, dtype=float)

    def arguments(self):
        return [self.arg]

    def eval(self, arglist):
        x = np.asarray(arglist[0], dtype=float)
        return float(np.sum(self.y / x - np.log(self.y / x) - 1.0))

    def grad(self, arglist):
        x = np.asarray(arglist[0], dtype=float)
        return [-self.y / (x ** 2) + 1.0 / x]
