# -*- coding: utf-8 -*-
#
# ADMM documentation build configuration file, created by
# sphinx-quickstart on Sat Jul 11 14:57:57 2015.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys
import os
import datetime
try:
    import sphinx_automodapi  # noqa: F401
except ImportError:
    pass

# Import metadata from setup.py
from descinfo import PACKAGE_NAME, PACKAGE_VERSION, AUTHOR, generate_definition_hrst
generate_definition_hrst()

# Try to override the matplotlib configuration as early as possible
try:
    import genrst
except ImportError:
    pass

# THEME
# RTD https://github.com/rtfd/sphinx_rtd_theme
import sphinx_rtd_theme  # @see https://github.com/rtfd/sphinx_rtd_theme

# TAG
try:
    from sphinx.util.tags import Tags
    tags = Tags()
    tags.add('all')
except (ImportError, NameError):
    try:
        tags.add('all')
    except NameError:
        pass

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
sys.path.append(os.path.dirname(__file__))

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinxcontrib.bibtex',
    'sphinx.ext.mathjax',
    'numpydoc',  # numpy docstring style
    'sphinx.ext.todo',
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    # 'sphinx.ext.ifconfig',
    # 'sphinx.ext.viewcode',
    # 'sphinx_gallery.gen_gallery',
    'sphinx.ext.autosummary',
    'language'
]

bibtex_bibfiles = []

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# generate autosummary even if no references
autosummary_generate = True

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
# source_suffix = ['.rst', '.md']
source_suffix = '.rst'

# The encoding of source files.
# source_encoding = 'utf-8-sig'

# The master toctree document.
root_doc = 'index'

# General information about the project.
project = PACKAGE_NAME
copyright = u'{}, Decision Intelligence Lab @ DAMO Academy'.format(datetime.date.today().strftime('%Y'))
author = AUTHOR

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

release = PACKAGE_VERSION

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# There are two options for replacing |today|: either, you set today to some
# non-false value, then it is used:
# today = ''
# Else, today_fmt is used as the format for a strftime call.
today_fmt = '%Y, %B %d'

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
exclude_patterns = [
    '_build',
    'sdk',
]

# The reST default role (used for this markup: `text`) to use for all
# documents.
# default_role = None

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
# add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'sphinx'

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

mdo_theme = 'RTD'

########################
# RTD                  #
########################
if mdo_theme == 'RTD':
    html_theme = 'sphinx_rtd_theme'
    # Add any paths that contain custom themes here, relative to this directory.
    html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]
    # RTD https://github.com/rtfd/sphinx_rtd_theme
    html_theme_options = {
        'collapse_navigation': False,  # False,
        'navigation_depth': 3,
    }

    # RTD.
    # on_rtd is whether we are on readthedocs.org, this line of code grabbed from docs.readthedocs.org
    on_rtd = os.environ.get('READTHEDOCS', None) == 'True'

    def setup(app):
        app.add_css_file('css/content_width.css')

    if on_rtd:
        html_context = {
            'css_files': [
                'https://media.readthedocs.org/css/sphinx_rtd_theme.css',
                'https://media.readthedocs.org/css/readthedocs-doc-embed.css',
            ],
        }

else:
    raise ValueError(f"Unknown theme: {mdo_theme}")

# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
html_title = u'{} {}'.format(project, release)

# A shorter title for the navigation bar.  Default is the same as html_title.
html_short_title = project

# The name of an image file (relative to this directory) to place at the top
# of the sidebar.
# html_logo = None
# html_logo = "logo/logo-only-32.png"

# The name of an image file (within the static path) to use as favicon of the
# docs.  This file should be a Windows icon file (.ico) being 16x16 or 32x32
# pixels large.
# html_favicon = None

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# html_static_path = ['output/html/_static']
html_static_path = ['_static']

# Add any extra paths that contain custom files (such as robots.txt or
# .htaccess) here, relative to this directory. These files are copied
# directly to the root of the documentation.
# html_extra_path = []

# If not '', a 'Last updated on:' timestamp is inserted at every page bottom,
# using the given strftime format.
html_last_updated_fmt = '%b %d, %Y'

# If true, SmartyPants will be used to convert quotes and dashes to
# typographically correct entities.
# html_use_smartypants = True

# Custom sidebar templates, maps document names to template names.
# html_sidebars = {}

# Additional templates that should be rendered to pages, maps page names to
# template names.
# html_additional_pages = {}

# If false, no module index is generated.
# html_domain_indices = True

# If false, no index is generated.
# html_use_index = True

# If true, the index is split into individual pages for each letter.
# html_split_index = False

# If true, links to the reST sources are added to the pages.
html_show_sourcelink = False

# If true, "Created using Sphinx" is shown in the HTML footer. Default is True.
# html_show_sphinx = True

# If true, "(C) Copyright ..." is shown in the HTML footer. Default is True.
html_show_copyright = True

# If true, an OpenSearch description file will be output, and all pages will
# contain a <link> tag referring to it.  The value of this option must be the
# base URL from which the finished HTML is served.
# html_use_opensearch = ''

# This is the file name suffix for HTML files (e.g. ".xhtml").
# html_file_suffix = None

# Language to be used for generating the HTML full-text search index.
# Sphinx supports the following languages:
#   'da', 'de', 'en', 'es', 'fi', 'fr', 'hu', 'it', 'ja'
#   'nl', 'no', 'pt', 'ro', 'ru', 'sv', 'tr'
# html_search_language = 'en'

# A dictionary with options for the search language support, empty by default.
# Now only 'ja' uses this config value
# html_search_options = {'type': 'default'}

# The name of a javascript file (relative to the configuration directory) that
# implements a search results scorer. If empty, the default will be used.
# html_search_scorer = 'scorer.js'

# Output file base name for HTML help builder.
htmlhelp_basename = 'ADMMDoc'

# -- Options for LaTeX output ---------------------------------------------

# Clean table style: top and bottom rules only, no row stripes.
latex_table_style = ['booktabs']

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    # 'papersize': 'letterpaper',

    # The font size ('10pt', '11pt' or '12pt').
    # The font size ('10pt', '11pt' or '12pt').
    # 'pointsize': '10pt',

    # Make the PDF more compact and avoid chapter-only blank pages.
    'extraclassoptions': 'oneside,openany',

    # Tighter margins (Sphinx default is ~1.5in).
    # Code blocks: no border, sharp corners, light gray background.
    'sphinxsetup': 'hmargin=1in,vmargin=1in,'
                   'pre_border-width=0pt,'
                   'pre_border-radius=0pt,'
                   'pre_padding=6pt,'
                   'pre_background-TeXcolor={RGB}{245,245,245}',

    # Additional stuff for the LaTeX preamble.
    'preamble': r'''
\usepackage{amssymb}
\usepackage[htt]{hyphenat}
\usepackage{xurl}
\usepackage{fancyvrb}
\usepackage{xcolor}
\usepackage{titlesec}
\usepackage{mathtools}

\definecolor{admmblue}{HTML}{1F4E79}
\hypersetup{
  colorlinks=true,
  linkcolor=admmblue,
  urlcolor=admmblue,
  citecolor=admmblue,
}

% Avoid stretched vertical whitespace at the bottom of pages.
\raggedbottom

% Give TeX more flexibility before producing ugly overfull lines.
\setlength{\emergencystretch}{3em}
\hfuzz=1pt
\vfuzz=2pt
\hbadness=2000
\vbadness=2000
\sloppy

% Tables: keep only top and bottom rules, remove header mid-rule.
\renewcommand{\midrule}{}

% Make code blocks slightly denser so they fit pages more gracefully.
\fvset{fontsize=\small,baselinestretch=0.95}

% Long API pages and index-like lists look better slightly compacted.
% Use cellspace for vertical centering with proper spacing
\usepackage{cellspace}
\setlength{\cellspacetoplimit}{0.4em}
\setlength{\cellspacebottomlimit}{0.4em}
\AtBeginEnvironment{longtable}{\small\renewcommand{\arraystretch}{1.75}}
\AtBeginEnvironment{tabulary}{\small\renewcommand{\arraystretch}{1.75}}
\AtBeginEnvironment{description}{\small}
\AtBeginEnvironment{tabular}{\renewcommand{\arraystretch}{1.75}}

% Fix cases environment in table cells: ensure braces render correctly
% Use dcases* from mathtools which handles display style better
\let\cases\dcases
\let\endcases\enddcases

% Keep cross-reference links in the surrounding text font.
\AtBeginDocument{\renewcommand{\sphinxcrossref}[1]{#1}}

% Make rubric blocks read more like landing-page feature headers in PDF.
\titleformat{\subsubsection}[block]
  {\large\sffamily\bfseries\color{admmblue}}
  {}
  {0pt}
  {}
  [\vspace{0.15em}\titlerule]
\titlespacing*{\subsubsection}{0pt}{1.2em}{0.6em}
''',

    # The generated PDF should end with the document content, not a back-of-book index.
    'makeindex': '',
    'printindex': '',

    # Latex figure (float) alignment
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (root_doc, 'ADMM.tex', u'ADMM User Manual',
     u'MindOpt Team', 'manual'),
]

# The name of an image file (relative to this directory) to place at the top of
# the title page.
# latex_logo = None

latex_engine = 'xelatex'
# Keep the PDF hierarchy aligned with the HTML/toctree structure.
# Blank-page behavior is already controlled by oneside/openany above.
latex_toplevel_sectioning = 'chapter'
# For "manual" documents, if this is true, then toplevel headings are parts,
# not chapters.
# latex_use_parts = False

# If true, show page references after internal links.
# latex_show_pagerefs = False

# If true, show URL addresses after external links.
# latex_show_urls = False

# Documents to append as an appendix to all manuals.
# latex_appendices = []

# If false, no module index is generated.
# latex_domain_indices = True


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (root_doc, 'ADMM', u'ADMM User Manual',
     [author], 1)
]

# If true, show URL addresses after external links.
# man_show_urls = False


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (root_doc, 'ADMM', u'ADMM User Manual',
     author, 'ADMM', 'Python library for structured optimization via ADMM.',
     'Miscellaneous'),
]

# Documents to append as an appendix to all manuals.
# texinfo_appendices = []

# If false, no module index is generated.
# texinfo_domain_indices = True

# How to display URL addresses: 'footnote', 'no', or 'inline'.
# texinfo_show_urls = 'footnote'

# If true, do not generate a @detailmenu in the "Top" node's menu.
# texinfo_no_detailmenu = False
